version: "3.8"

services:
  app:
    build: ./app
    container_name: flask_app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    volumes:
      - ./app:/app
